/* ═══════════════════════════════════════════════════════
   CLAW DEVOPS AGENT v2 — core.js
   Global state, constants, helpers, event bus
═══════════════════════════════════════════════════════ */

const ANTHROPIC_API   = "https://api.anthropic.com/v1/messages";
const MODEL           = "claude-sonnet-4-20250514";
const HIGH_RISK_TOOLS = ["github_create_pr","render_trigger_deploy","supabase_run_migration"];

const COLORS = {
  green:"#0fd98a",  greenDim:"rgba(15,217,138,0.12)",
  red:"#f43060",    redDim:"rgba(244,48,96,0.12)",
  yellow:"#f5a623", yellowDim:"rgba(245,166,35,0.12)",
  cyan:"#18d4f0",   cyanDim:"rgba(24,212,240,0.10)",
  purple:"#9c7df5", purpleDim:"rgba(156,125,245,0.12)",
  accent:"#2f78f0", accentDim:"rgba(47,120,240,0.12)",
  text:"#c0d0e8",   textDim:"#3d5570", textMid:"#6a8aaa",
};

/* ── API KEYS ──────────────────────────────────────── */
const KEYS = {
  anthropic:"", github:"", githubRepo:"",
  render:"",    renderService:"",
  supabaseUrl:"", supabase:"",
};
const KEY_STATUS = { anthropic:"none", github:"none", render:"none", supabase:"none" };

function loadKeys() {
  try { Object.assign(KEYS, JSON.parse(localStorage.getItem("claw_api_keys") || "{}")); } catch(e) {}
}
function persistKeys() { localStorage.setItem("claw_api_keys", JSON.stringify(KEYS)); }
function isConfigured() { return KEYS.anthropic.length > 10; }

/* ── GLOBAL STATE ─────────────────────────────────── */
const STATE = {
  tab: "dashboard",
  metrics:      { cpu:34, mem:48, disk:22, net:67 },
  ghStatus:     { branch:"main", lastCommit:"fix: auth middleware", sha:"abc1234", ci:"passing", openPRs:3, issues:7 },
  renderStatus: { status:"live", uptime:"99.8%", url:"myapp.onrender.com", lastDeploy:"há 2h", region:"us-east" },
  sbStatus:     { status:"connected", latency:18, tables:14, rows:"42.3k", storage:"128 MB", connections:"12/20" },
  workflows:[
    { name:"CI/CD Pipeline",  status:"success", duration:"3m 42s", ago:"há 2h" },
    { name:"Test Suite",       status:"success", duration:"1m 18s", ago:"há 2h" },
    { name:"Deploy to Render", status:"running", duration:"—",      ago:"agora" },
    { name:"DB Migrations",    status:"success", duration:"8s",     ago:"há 1d" },
  ],
  logs:[], errors:[],
  pending:[
    { id:"act-001", toolName:"github_create_pr", risk:"high", autoGenerated:true,
      description:"Criar PR: 'fix: auto-correção de unhandled promise' na branch autofix/error-001",
      input:{ title:"fix: auto-correção de unhandled promise", branch:"autofix/error-001" } },
    { id:"act-002", toolName:"render_trigger_deploy", risk:"high", autoGenerated:false,
      description:"Redeploy no Render: após correção de auth middleware",
      input:{ reason:"após correção de auth middleware" } },
  ],
  agentMsgs:[
    { role:"assistant", text:"Claw DevOps Agent online.\n\nMonitorando GitHub, Render e Supabase em tempo real.\nDetectei 1 erro não tratado nos logs do Render — PR de correção preparado e aguardando aprovação.\n\nPosso também editar seus arquivos de código diretamente — acesse a aba ✎ Editor.\n\nO que deseja fazer?" }
  ],
  agentHistory:[], agentLoading:false,
  files:{}, activeFile:null, modifiedFiles:new Set(),
  lastAlertMsg:null,
};

/* ── EVENT BUS ────────────────────────────────────── */
const Bus = {
  _l:{},
  on(e,fn)  { (this._l[e]=this._l[e]||[]).push(fn); },
  off(e,fn) { this._l[e]=(this._l[e]||[]).filter(f=>f!==fn); },
  emit(e,d) { (this._l[e]||[]).forEach(fn=>fn(d)); },
};

/* ── HELPERS ─────────────────────────────────────── */
function escHtml(s){ return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }
function escAttr(s){ return String(s??"").replace(/'/g,"\\'").replace(/[<>]/g,""); }
function _el(id){ return document.getElementById(id); }

function statusColor(s=""){
  const l=s.toLowerCase();
  if(/live|ok|success|passing|connected|active/.test(l)) return COLORS.green;
  if(/fail|error|down|crash|critical/.test(l))           return COLORS.red;
  if(/pending|running|deploy|building|warn|high/.test(l)) return COLORS.yellow;
  if(/medium/.test(l))                                    return COLORS.cyan;
  return COLORS.purple;
}
function levelColor(lvl){ return {info:COLORS.cyan,warn:COLORS.yellow,error:COLORS.red,success:COLORS.green,agent:COLORS.purple}[lvl]||COLORS.text; }
function timePT(){ return new Date().toLocaleTimeString("pt-BR",{hour12:false}); }
function badge(text,color){ const c=color||statusColor(text); return `<span class="badge" style="background:${c}18;color:${c};border:1px solid ${c}30;">${escHtml(text)}</span>`; }
function dot(color,pulse=false){ const g=`box-shadow:0 0 8px ${color};`; return `<span class="dot${pulse?" pulse":""}" style="background:${color};${pulse?g:""}"></span>`; }
function metricBox(label,value,color,sub){ const c=color||COLORS.text; return `<div class="metric-box"><div class="m-label">${escHtml(label)}</div><div class="m-value" style="color:${c}">${escHtml(String(value))}</div>${sub?`<div class="m-sub">${escHtml(sub)}</div>`:""}</div>`; }
function progressBar(label,value,color){ const c=color||COLORS.accent; const v=Math.min(100,Math.max(0,Math.round(value))); return `<div class="progress-wrap"><div class="progress-header"><span>${escHtml(label)}</span><span style="color:${c}">${v}%</span></div><div class="progress-track"><div class="progress-fill" style="width:${v}%;background:${c};"></div></div></div>`; }
function listRow(dc,pulse,title,sub,right){ return `<div class="list-row">${dot(dc,pulse)}<div class="row-main"><div class="row-title">${escHtml(title)}</div>${sub?`<div class="row-sub">${escHtml(sub)}</div>`:""}</div>${right||""}</div>`; }
function cpuColor(cpu){ return cpu>80?COLORS.red:cpu>60?COLORS.yellow:COLORS.green; }

/* ── LOG SYSTEM ─────────────────────────────────── */
function addLog(level,source,message){
  const entry={id:Date.now()+Math.random(),level,source,message,time:timePT()};
  STATE.logs.push(entry);
  if(STATE.logs.length>600) STATE.logs=STATE.logs.slice(-600);
  if(level==="error"){
    STATE.errors.push(entry);
    if(STATE.errors.length>100) STATE.errors=STATE.errors.slice(-100);
    Bus.emit("critical-error",entry);
  }
  Bus.emit("log-new",entry);
  Bus.emit("badges-update");
}

/* ── SEED LOGS ───────────────────────────────────── */
(function seedLogs(){
  const seed=[
    ["info","MONITOR","GitHub CI: passing | Render: live | Supabase: ok (18ms)"],
    ["info","RENDER","Health check OK — 142 req/min"],
    ["info","SUPABASE","Pool: 12/20 conexões ativas"],
    ["info","GITHUB","Webhook: push → main (abc1234)"],
    ["warn","RENDER","Deploy demorando mais que o esperado"],
    ["error","RENDER-LOG","UnhandledPromiseRejection: Cannot read property 'id' of undefined"],
    ["info","AUTO-FIX","Analisando erro detectado..."],
    ["info","AGENT","Tool: render_get_logs | Risco: low → executando"],
    ["success","APPROVAL","PR #47 aprovado e criado com sucesso"],
    ["info","MONITOR","Backup Supabase agendado para 03:00"],
  ];
  const now=Date.now();
  seed.forEach(([level,source,message],i)=>{
    const entry={id:i,level,source,message,time:new Date(now-(seed.length-i)*45000).toLocaleTimeString("pt-BR",{hour12:false})};
    STATE.logs.push(entry);
    if(level==="error") STATE.errors.push(entry);
  });
})();

/* ── LIVE SIMULATION ─────────────────────────────── */
(function startSim(){
  const msgs=[
    ["info","MONITOR","GitHub=passing | Render=live | Supabase=ok (18ms)"],
    ["info","RENDER","142 req/min | P99: 89ms"],
    ["warn","RENDER","Memory spike: 78%"],
    ["info","SUPABASE","Pool connections: 12/20"],
    ["error","RENDER-LOG","TypeError: Cannot read properties of undefined (reading 'userId')"],
    ["info","AUTO-FIX","Erro detectado — iniciando análise com Claude AI"],
    ["info","GITHUB","CI check passou: test-suite (1m 18s)"],
    ["info","MONITOR","Backup agendado: 03:00 UTC"],
  ];
  let i=0;
  setInterval(()=>{ const [l,s,m]=msgs[i%msgs.length]; addLog(l,s,m); i++; },4500);
})();

/* ── METRIC ANIMATION ────────────────────────────── */
(function animateMetrics(){
  setInterval(()=>{
    const m=STATE.metrics;
    STATE.metrics={
      cpu:Math.max(5,Math.min(95,m.cpu+(Math.random()-.5)*10)),
      mem:Math.max(20,Math.min(90,m.mem+(Math.random()-.5)*5)),
      disk:Math.max(10,Math.min(80,m.disk+(Math.random()-.5)*2)),
      net:Math.max(10,Math.min(95,m.net+(Math.random()-.5)*15)),
    };
    Bus.emit("metrics-update");
  },3200);
})();
